name: SDB

on:
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
    build-and-test:
        strategy:
            matrix:
                name: [ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.name }}
        steps:
            - name: Install Meson + Ninja
              run: sudo pip3 install meson ninja

            - uses: actions/checkout@v2
            - name: Running mmap build
              run: |
                  meson build-mmap
                  ninja -C build-mmap
                  
            - name: Testing mmap build
              run: ninja -C build-mmap test
                  
            - name: Running non-mmap build
              env:
                  CFLAGS: -DUSE_MMAN=-0
                  VERBOSE: 1
              run: |
                  meson build-nommap
                  ninja -C build-nommap
                  
            - name: Testing non-mmap build
              run: ninja -C build-nommap test
